#ifndef LIBTESTING_ENUMS_H
#define LIBTESTING_ENUMS_H

enum _LIBTESTING_STATUS_ {
	STATUS_NOT_TESTED 	= 0,
	STATUS_FAILED	  	= 1,
	STATUS_OK		  	= 2,
	STATUS_PASSED	  	= 3,
	STATUS_TESTED 		= 127,
};

enum _LIBTESTING_TYPE_ {
	TYPE_UNDEFINED		= 0,
	TYPE_NUMERIC		= 1,
	TYPE_BOOLEAN		= 2,
};

enum _LIBTESTING_PARAMETER_ {
	ST_NAME				= 0,
	ST_STATUS			= 1,
	ST_TYPE				= 2,
	ST_ITERCOUNT		= 3,
	ST_MAETHRESHOLD		= 4,
	ST_MSETHRESHOLD		= 5,
	ST_RMSETHRESHOLD	= 6,
	ST_MRETHRESHOLD		= 7,
	ST_PASSTHRESHOLD	= 8,
	ST_TESTFUNCTION 	= 9,
	ST_THRESHOLDFLAG	= 10,
	ST_WORSTCRITERIA	= 11,

	TU_EXPORTPATH		= 64,
};

enum _LIBTESTING_THRESHOLD_ {
	THRES_MAE			= 0x1,
	THRES_MSE			= 0x2,
	THRES_MRE			= 0x4,
	THRES_RMSE			= 0x8,
};

enum _LIBTESTING_WORST_ {
	WORST_NONE			= 0,
	WORST_AE			= 1,
	WORST_SE			= 2,
	WORST_RE			= 3,
};

enum _LIBTESTING_ERRORS_ {
	ERROR_MALLOC		= 0,
	ERROR_ZERO_LENGTH 	= 1,
	ERROR_NULL_POINTER 	= 2,
	ERROR_ITER_ZERO 	= 3,
	ERROR_TYPE_UNDEF 	= 4,
	ERROR_INDEX_TOOBIG 	= 5,
	ERROR_FILE			= 6,
	ERROR_NOTTESTED		= 7,
};

enum _LIBTESTING_INFOS_ {
	INFO_FILE_SUCCESS		= 0,
	INFO_SKIPPED_TEST		= 1,
	INFO_EXPORT_PATH_UNSET 	= 2,
};

enum _LIBTESTING_HISTOGRAM_ {
	HISTOGRAM_MAE		= 0,
	HISTOGRAM_MSE		= 1,
	HISTOGRAM_RMSE		= 2,
	HISTOGRAM_MRE		= 3,
};

enum _LIBTESTING_UNIT_FLAG_ {
	UNITFLAG_SKIP_TEST 		= 0x1,
	UNITFLAG_LOG_RESULTS	= 0x2,
	UNITFLAG_SHOW_HISTO_MAE = 0x4,
	UNITFLAG_SHOW_HISTO_MRE = 0x8,
	UNITFLAG_SHOW_HISTO_MSE = 0x10,
	UNITFLAG_EXPORT_CSV 	= 0x20,
};

#endif  // LIBTESTING_ENUMS_H
