#ifndef TERMCOLOR_H
#define TERMCOLOR_H 1

#define ANSI_ESCAPE "\x1b"
#define NO_STRING

//#define _WIN32 1

#ifdef _WIN32
	#define SET_STYLE(x, y, z) 	NO_STRING
	#define RESET_STYLE 		NO_STRING
#else
	#define SET_STYLE(x, y, z) 	ANSI_ESCAPE "[" x ";3" y ";4" z "m"
	#define RESET_STYLE 		ANSI_ESCAPE "[0m"
	#define SET_FG(x) 	        ANSI_ESCAPE "[;3" x "m"
	#define SET_BG(x) 	        ANSI_ESCAPE "[;4" x "m"
	#define SET_BG_FG(x) 	    ANSI_ESCAPE "[3" x ";4" x "m"
#endif // _WIN32

#define COLOR_BLACK 	"0"
#define COLOR_RED 		"1"
#define COLOR_GREEN 	"2"
#define COLOR_YELLOW 	"3"
#define COLOR_BLUE 		"4"
#define COLOR_MAGENTA 	"5"
#define COLOR_CYAN 		"6"
#define COLOR_WHITE 	"7"
#define COLOR_DEFAULT 	"9"

#define STYLE_NORMAL	"0"
#define STYLE_BOLD		"1"
#define STYLE_DIM		"2"
#define STYLE_ITALIC	"3"
#define STYLE_UNDERLINE	"4"
#define STYLE_BLINKING	"5"
#define STYLE_REVERSE	"7"
#define STYLE_HIDDEN	"8"
#define STYLE_STRIKE	"9"

#define NORMAL_BLACK 	SET_STYLE(STYLE_NORMAL, COLOR_BLACK, 	COLOR_DEFAULT)
#define NORMAL_RED 		SET_STYLE(STYLE_NORMAL, COLOR_RED, 		COLOR_DEFAULT)
#define NORMAL_GREEN 	SET_STYLE(STYLE_NORMAL, COLOR_GREEN, 	COLOR_DEFAULT)
#define NORMAL_YELLOW 	SET_STYLE(STYLE_NORMAL, COLOR_YELLOW, 	COLOR_DEFAULT)
#define NORMAL_BLUE 	SET_STYLE(STYLE_NORMAL, COLOR_BLUE, 	COLOR_DEFAULT)
#define NORMAL_MAGENTA 	SET_STYLE(STYLE_NORMAL, COLOR_MAGENTA,	COLOR_DEFAULT)
#define NORMAL_CYAN 	SET_STYLE(STYLE_NORMAL, COLOR_CYAN, 	COLOR_DEFAULT)
#define NORMAL_WHITE 	SET_STYLE(STYLE_NORMAL, COLOR_WHITE, 	COLOR_DEFAULT)
#define NORMAL_DEFAULT 	SET_STYLE(STYLE_NORMAL, COLOR_DEFAULT,	COLOR_DEFAULT)

#define BOLD_BLACK 		SET_STYLE(STYLE_BOLD, 	COLOR_BLACK, 	COLOR_DEFAULT)
#define BOLD_RED 		SET_STYLE(STYLE_BOLD, 	COLOR_RED, 		COLOR_DEFAULT)
#define BOLD_GREEN 		SET_STYLE(STYLE_BOLD, 	COLOR_GREEN, 	COLOR_DEFAULT)
#define BOLD_YELLOW 	SET_STYLE(STYLE_BOLD, 	COLOR_YELLOW, 	COLOR_DEFAULT)
#define BOLD_BLUE 		SET_STYLE(STYLE_BOLD, 	COLOR_BLUE, 	COLOR_DEFAULT)
#define BOLD_MAGENTA 	SET_STYLE(STYLE_BOLD, 	COLOR_MAGENTA,	COLOR_DEFAULT)
#define BOLD_CYAN 		SET_STYLE(STYLE_BOLD, 	COLOR_CYAN, 	COLOR_DEFAULT)
#define BOLD_WHITE 		SET_STYLE(STYLE_BOLD, 	COLOR_WHITE, 	COLOR_DEFAULT)
#define BOLD_DEFAULT 	SET_STYLE(STYLE_BOLD, 	COLOR_DEFAULT,	COLOR_DEFAULT)

#define DIM_BLACK 		SET_STYLE(STYLE_DIM, 	COLOR_BLACK, 	COLOR_DEFAULT)
#define DIM_RED 		SET_STYLE(STYLE_DIM, 	COLOR_RED, 		COLOR_DEFAULT)
#define DIM_GREEN 		SET_STYLE(STYLE_DIM, 	COLOR_GREEN, 	COLOR_DEFAULT)
#define DIM_YELLOW 		SET_STYLE(STYLE_DIM, 	COLOR_YELLOW, 	COLOR_DEFAULT)
#define DIM_BLUE 		SET_STYLE(STYLE_DIM, 	COLOR_BLUE, 	COLOR_DEFAULT)
#define DIM_MAGENTA 	SET_STYLE(STYLE_DIM, 	COLOR_MAGENTA,	COLOR_DEFAULT)
#define DIM_CYAN 		SET_STYLE(STYLE_DIM, 	COLOR_CYAN, 	COLOR_DEFAULT)
#define DIM_WHITE 		SET_STYLE(STYLE_DIM, 	COLOR_WHITE, 	COLOR_DEFAULT)
#define DIM_DEFAULT 	SET_STYLE(STYLE_DIM, 	COLOR_DEFAULT,	COLOR_DEFAULT)

#define ITALIC_BLACK 	SET_STYLE(STYLE_ITALIC, COLOR_BLACK, 	COLOR_DEFAULT)
#define ITALIC_RED 		SET_STYLE(STYLE_ITALIC, COLOR_RED, 		COLOR_DEFAULT)
#define ITALIC_GREEN 	SET_STYLE(STYLE_ITALIC, COLOR_GREEN, 	COLOR_DEFAULT)
#define ITALIC_YELLOW 	SET_STYLE(STYLE_ITALIC, COLOR_YELLOW, 	COLOR_DEFAULT)
#define ITALIC_BLUE 	SET_STYLE(STYLE_ITALIC, COLOR_BLUE, 	COLOR_DEFAULT)
#define ITALIC_MAGENTA 	SET_STYLE(STYLE_ITALIC, COLOR_MAGENTA,	COLOR_DEFAULT)
#define ITALIC_CYAN 	SET_STYLE(STYLE_ITALIC, COLOR_CYAN, 	COLOR_DEFAULT)
#define ITALIC_WHITE 	SET_STYLE(STYLE_ITALIC, COLOR_WHITE, 	COLOR_DEFAULT)
#define ITALIC_DEFAULT 	SET_STYLE(STYLE_ITALIC, COLOR_DEFAULT,	COLOR_DEFAULT)

#define UNDERLINE_BLACK 	SET_STYLE(STYLE_UNDERLINE, 	COLOR_BLACK, 	COLOR_DEFAULT)
#define UNDERLINE_RED 		SET_STYLE(STYLE_UNDERLINE, 	COLOR_RED, 		COLOR_DEFAULT)
#define UNDERLINE_GREEN 	SET_STYLE(STYLE_UNDERLINE, 	COLOR_GREEN, 	COLOR_DEFAULT)
#define UNDERLINE_YELLOW 	SET_STYLE(STYLE_UNDERLINE, 	COLOR_YELLOW, 	COLOR_DEFAULT)
#define UNDERLINE_BLUE 		SET_STYLE(STYLE_UNDERLINE, 	COLOR_BLUE, 	COLOR_DEFAULT)
#define UNDERLINE_MAGENTA 	SET_STYLE(STYLE_UNDERLINE, 	COLOR_MAGENTA,	COLOR_DEFAULT)
#define UNDERLINE_CYAN 		SET_STYLE(STYLE_UNDERLINE, 	COLOR_CYAN, 	COLOR_DEFAULT)
#define UNDERLINE_WHITE 	SET_STYLE(STYLE_UNDERLINE, 	COLOR_WHITE, 	COLOR_DEFAULT)
#define UNDERLINE_DEFAULT 	SET_STYLE(STYLE_UNDERLINE, 	COLOR_DEFAULT,	COLOR_DEFAULT)

#define BLINKING_BLACK 		SET_STYLE(STYLE_BLINKING, 	COLOR_BLACK, 	COLOR_DEFAULT)
#define BLINKING_RED 		SET_STYLE(STYLE_BLINKING, 	COLOR_RED, 		COLOR_DEFAULT)
#define BLINKING_GREEN 		SET_STYLE(STYLE_BLINKING, 	COLOR_GREEN, 	COLOR_DEFAULT)
#define BLINKING_YELLOW 	SET_STYLE(STYLE_BLINKING, 	COLOR_YELLOW, 	COLOR_DEFAULT)
#define BLINKING_BLUE 		SET_STYLE(STYLE_BLINKING, 	COLOR_BLUE, 	COLOR_DEFAULT)
#define BLINKING_MAGENTA 	SET_STYLE(STYLE_BLINKING, 	COLOR_MAGENTA,	COLOR_DEFAULT)
#define BLINKING_CYAN 		SET_STYLE(STYLE_BLINKING, 	COLOR_CYAN, 	COLOR_DEFAULT)
#define BLINKING_WHITE 		SET_STYLE(STYLE_BLINKING, 	COLOR_WHITE, 	COLOR_DEFAULT)
#define BLINKING_DEFAULT 	SET_STYLE(STYLE_BLINKING, 	COLOR_DEFAULT,	COLOR_DEFAULT)

#define REVERSE_BLACK 	SET_STYLE(STYLE_REVERSE, 	COLOR_BLACK, 	COLOR_DEFAULT)
#define REVERSE_RED 	SET_STYLE(STYLE_REVERSE, 	COLOR_RED, 		COLOR_DEFAULT)
#define REVERSE_GREEN 	SET_STYLE(STYLE_REVERSE, 	COLOR_GREEN, 	COLOR_DEFAULT)
#define REVERSE_YELLOW 	SET_STYLE(STYLE_REVERSE, 	COLOR_YELLOW, 	COLOR_DEFAULT)
#define REVERSE_BLUE 	SET_STYLE(STYLE_REVERSE, 	COLOR_BLUE, 	COLOR_DEFAULT)
#define REVERSE_MAGENTA SET_STYLE(STYLE_REVERSE, 	COLOR_MAGENTA,	COLOR_DEFAULT)
#define REVERSE_CYAN 	SET_STYLE(STYLE_REVERSE, 	COLOR_CYAN, 	COLOR_DEFAULT)
#define REVERSE_WHITE 	SET_STYLE(STYLE_REVERSE, 	COLOR_WHITE, 	COLOR_DEFAULT)
#define REVERSE_DEFAULT SET_STYLE(STYLE_REVERSE, 	COLOR_DEFAULT,	COLOR_DEFAULT)

#define HIDDEN_BLACK 	SET_STYLE(STYLE_HIDDEN, 	COLOR_BLACK, 	COLOR_DEFAULT)
#define HIDDEN_RED 		SET_STYLE(STYLE_HIDDEN, 	COLOR_RED, 		COLOR_DEFAULT)
#define HIDDEN_GREEN 	SET_STYLE(STYLE_HIDDEN, 	COLOR_GREEN, 	COLOR_DEFAULT)
#define HIDDEN_YELLOW 	SET_STYLE(STYLE_HIDDEN, 	COLOR_YELLOW, 	COLOR_DEFAULT)
#define HIDDEN_BLUE 	SET_STYLE(STYLE_HIDDEN, 	COLOR_BLUE, 	COLOR_DEFAULT)
#define HIDDEN_MAGENTA 	SET_STYLE(STYLE_HIDDEN, 	COLOR_MAGENTA,	COLOR_DEFAULT)
#define HIDDEN_CYAN 	SET_STYLE(STYLE_HIDDEN, 	COLOR_CYAN, 	COLOR_DEFAULT)
#define HIDDEN_WHITE 	SET_STYLE(STYLE_HIDDEN, 	COLOR_WHITE, 	COLOR_DEFAULT)
#define HIDDEN_DEFAULT 	SET_STYLE(STYLE_HIDDEN, 	COLOR_DEFAULT,	COLOR_DEFAULT)

#define STRIKE_BLACK 	SET_STYLE(STYLE_STRIKE, 	COLOR_BLACK, 	COLOR_DEFAULT)
#define STRIKE_RED 		SET_STYLE(STYLE_STRIKE, 	COLOR_RED, 		COLOR_DEFAULT)
#define STRIKE_GREEN 	SET_STYLE(STYLE_STRIKE, 	COLOR_GREEN, 	COLOR_DEFAULT)
#define STRIKE_YELLOW 	SET_STYLE(STYLE_STRIKE, 	COLOR_YELLOW, 	COLOR_DEFAULT)
#define STRIKE_BLUE 	SET_STYLE(STYLE_STRIKE, 	COLOR_BLUE, 	COLOR_DEFAULT)
#define STRIKE_MAGENTA 	SET_STYLE(STYLE_STRIKE, 	COLOR_MAGENTA,	COLOR_DEFAULT)
#define STRIKE_CYAN 	SET_STYLE(STYLE_STRIKE, 	COLOR_CYAN, 	COLOR_DEFAULT)
#define STRIKE_WHITE 	SET_STYLE(STYLE_STRIKE, 	COLOR_WHITE, 	COLOR_DEFAULT)
#define STRIKE_DEFAULT 	SET_STYLE(STYLE_STRIKE, 	COLOR_DEFAULT,	COLOR_DEFAULT)

#else
#endif // TERMCOLOR_H
